### PR TITLE
Stop folding non-setter methods into ObjectMapper builder

### LINKED ISSUE #130: ObjectMapper to JsonMapper breaks completly (messed up code)
## What version of OpenRewrite are you using?

I am using

- Maven/plugin v6.36.0

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>6.36.0</version>
                <configuration>
                    <exportDatatables>true</exportDatatables>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.spring.boot4.UpgradeSpringBoot_4_0</recipe>
                    </activeRecipes>

                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-spring</artifactId>
                        <version>6.29.0</version>
                    </dependency>
                </dependencies>
            </plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
        ObjectMapper mapper = new ObjectMapper();
        String customProperties;

        try {
            customProperties = mapper.writeValueAsString(customPropertyMap);
        } catch (JsonProcessingException ex) {
...

```

## What did you expect to see?

```java
        JsonMapper mapper = JsonMapper.builder().build();

        String customProperties;

        try {
            customProperties = mapper.writeValueAsString(customPropertyMap);
        } catch (JacksonException ex) {
```

## What did you see instead?

```java
        ObjectMapper mapper = JsonMapper.builder()
                // TODO writeValueAsString was removed from JsonMapper in Jackson 3.
                .writeValueAsString(customPropertyMap)
                .build();

        String customProperties;

        try {
            customProperties;
        } catch (JacksonException ex) {
```

## What is the full stack trace of any errors you encountered?

```
stacktrace output here
```

As i checked writeValueAsString is still available something with the spring boot migration went wrong i guess i got the issue at multiple locations i got no errors in stacktrace but would still consider this a bug

### PR DESCRIPTION
**Pull request by Jenson3210**
## Summary
- `MigrateMapperSettersToBuilder` was incorrectly collecting operational methods like `readValue()` and `writeValueAsString()` as standalone setters, folding them into the builder chain and corrupting code
- Added a return type check in `collectStandaloneSetters`: unknown methods (not in `SetterToBuilderMapping`) that don't return `void` or an `ObjectMapper`-assignable type stop collection. Known setters are always collected regardless of return type
- Added tests for both reported scenarios

- Closes https://github.com/moderneinc/customer-requests/issues/2225
- Closes https://github.com/openrewrite/rewrite-jackson/issues/130

## Test plan
- [x] Existing tests pass (31 Java + Kotlin tests)
- [x] New test: `readValueNotFoldedIntoBuilder` — setters folded, `readValue` assignment preserved
- [x] New test: `writeValueAsStringNotFoldedIntoBuilder` — no setters, no change, `writeValueAsString` in try block untouched

### CODE REVIEW

File: src/main/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilder.java [hunk 1]
```diff
@@ -310,6 +310,18 @@ private boolean isCallOnVariable(J.MethodInvocation mi, J.Identifier varIdent) {
...
+                    private boolean isSetterReturnType(J.MethodInvocation mi) {
+                        JavaType.Method methodType = mi.getMethodType();
+                        if (methodType == null) {
+                            return false;
+                        }
+                        JavaType returnType = methodType.getReturnType();
+                        if (returnType == JavaType.Primitive.Void) {
+                            return true;
+                        }
+                        return TypeUtils.isAssignableTo("com.fasterxml.jackson.databind.ObjectMapper", returnType);
```
Comment (steve-aom-elliott) [inline src/main/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilder.java:322]: So we'd return true if it's basically a chaining method? Hmm

Comment (Jenson3210) [reply src/main/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilder.java:322]: Notice that we only call this method when we do not find a setter: https://github.com/openrewrite/rewrite-jackson/blob/2b4cebdde833bf728b5d383068c88dc29f5ee754/src/main/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilder.java#L500

So the impact would be rather low. All methods which are used to return something would return false -> stop chaining

Comment (steve-aom-elliott) [reply src/main/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilder.java:322]: If we assume the method we come across doesn't appear in the `SetterToBuilderMapping`, which would cause the first part of the check on line 500 to pass, but the method has a return type of `com.fasterxml.jackson.databind.ObjectMapper`, wouldn't it also return true from `isSetterReturnType(..)`, meaning the part of the check on line 501 would fail out of the condition and not set `collecting` to `false`?

Comment (Jenson3210) [reply src/main/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilder.java:322]: if the method returns and ObjectMapper, it most likely is a chained "setter" method, no? In that case we also want to keep collecting

Comment (steve-aom-elliott) [reply src/main/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilder.java:322]: I suppose that would likely just be a setter we didn't account for in the `SetterToBuilderMapping` in that case, or potentially one that no longer exists or doesn't map, fair enough.

**Review by steve-aom-elliott — APPROVED** [review]
