### PR TITLE
Fix Kotlin MapperBuilder changeDefaultPropertyInclusion matching

### LINKED ISSUE #89: Kotlin: Jackson 2 to 3 Migration should replace `setSerializationInclusion` with `changeDefaultPropertyInclusion`
## What version of OpenRewrite are you using?
I am using

- Moderne CLI 3.57.12

## How are you running OpenRewrite?

I am using mod cli. In this case 

```bash
mod run . --recipe UpgradeSpringBoot_4_0
```

Project is maven multi-module 

## Kotlin Version
* Kotlin: 2.2.21
* Coroutines: 1.10.2

## What is the smallest, simplest way to reproduce the problem?
```kotlin
fun objectMapper(): ObjectMapper {
    return ObjectMapper()
            .registerKotlinModule()
            .registerModule(JavaTimeModule())
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .setTimeZone(TimeZone.getDefault())
            .setSerializationInclusion(JsonInclude.Include.NON_NULL)
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
}
```

## What did you expect to see?
```kotlin
fun objectMapper(): JsonMapper {
    return JsonMapper.builder()
        .addModule(kotlinModule())
        .defaultTimeZone(TimeZone.getDefault())
        .changeDefaultPropertyInclusion { incl -> incl.withValueInclusion(JsonInclude.Include.NON_NULL) }
        .changeDefaultPropertyInclusion { incl -> incl.withContentInclusion(JsonInclude.Include.NON_NULL) }
        .build()
}

```

## What did you see instead?
```kotlin
fun objectMapper(): ObjectMapper {
    returnObjectMapper()
        .registerKotlinModule()
        .setTimeZone(TimeZone.getDefault())
        .setDefaultPropertyInclusion(JsonInclude.Include.NON_NULL)
}
```

### Before
```kotlin
val objectMapper: ObjectMapper by lazy {
    ObjectMapper()
        .registerKotlinModule()
        .registerModule(JavaTimeModule())
        .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
        .setTimeZone(TimeZone.getDefault())
        .setSerializationInclusion(JsonInclude.Include.NON_NULL)
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
}
```

### After
```kotlin
val objectMapper: ObjectMapper by lazy {ObjectMapper()
        .registerKotlinModule()
        .setTimeZone(TimeZone.getDefault())
        .setDefaultPropertyInclusion(JsonInclude.Include.NON_NULL)
}
```

### Expected
```kotlin
val objectMapper: JsonMapper by lazy {
    JsonMapper.builder()
        .addModule(kotlinModule())
        .defaultTimeZone(TimeZone.getDefault())
        .changeDefaultPropertyInclusion { incl -> incl.withValueInclusion(JsonInclude.Include.NON_NULL) }
        .changeDefaultPropertyInclusion { incl -> incl.withContentInclusion(JsonInclude.Include.NON_NULL) }
        .build()
}
```

### PR DESCRIPTION
**Pull request by timtebeek**
## Summary

- Enable `matchOverrides` on the MapperBuilder `MethodMatcher` so `serializationInclusion` is matched when Kotlin resolves the declaring type as `JsonMapper$Builder` instead of `MapperBuilder`
- Fix lambda parameter type info for Kotlin AST compatibility
- Add Kotlin test for the MapperBuilder `serializationInclusion` → `changeDefaultPropertyInclusion` transformation

## Problem

The `UpdateSerializationInclusionConfiguration` recipe's MapperBuilder path silently skipped Kotlin source files. The Kotlin parser resolves `serializationInclusion()` declaring type as `JsonMapper$Builder` (concrete subclass), while the Java parser resolves it as `MapperBuilder` (where the method is declared). The `MethodMatcher` pattern `..MapperBuilder` matched by name only and didn't find `JsonMapper$Builder`.

Additionally, the `JavaTemplate`-generated lambda parameter lacked type info, which fails Kotlin AST type validation.

## Solution

1. Added `matchOverrides=true` to the `MethodMatcher` constructor, enabling subclass type matching
2. Added a post-processing step that sets `JsonInclude$Value` type on the lambda parameter variable

## Test plan

- [x] New Kotlin test `updateSerializationInclusionOnBuilder` passes
- [x] Existing Java tests pass unchanged
- [x] Existing Kotlin tests pass unchanged

- Fixes openrewrite/rewrite-jackson#89

### CODE REVIEW

File: src/test/java/org/openrewrite/java/jackson/KotlinUpgradeJackson_2_3Test.java [hunk 1]
```diff
@@ -116,4 +116,34 @@ fun objectMapper(): ObjectMapper {
...
+                      .build()
+              }
+              """,
+            """
+              import com.fasterxml.jackson.annotation.JsonInclude
+              import com.fasterxml.jackson.databind.json.JsonMapper
+
+              fun configure(): JsonMapper {
+                  return JsonMapper.builder()
+                      .changeDefaultPropertyInclusion({ incl ->incl.withContentInclusion(JsonInclude.Include.NON_NULL).withValueInclusion(JsonInclude.Include.NON_NULL)})
```
Comment (jaykhimani) [inline src/test/java/org/openrewrite/java/jackson/KotlinUpgradeJackson_2_3Test.java]: Missing space after `->`
