### PR TITLE
Handle fluent-chained setter calls in MigrateMapperSettersToBuilder

### LINKED ISSUE #89: Kotlin: Jackson 2 to 3 Migration should replace `setSerializationInclusion` with `changeDefaultPropertyInclusion`
## What version of OpenRewrite are you using?
I am using

- Moderne CLI 3.57.12

## How are you running OpenRewrite?

I am using mod cli. In this case 

```bash
mod run . --recipe UpgradeSpringBoot_4_0
```

Project is maven multi-module 

## Kotlin Version
* Kotlin: 2.2.21
* Coroutines: 1.10.2

## What is the smallest, simplest way to reproduce the problem?
```kotlin
fun objectMapper(): ObjectMapper {
    return ObjectMapper()
            .registerKotlinModule()
            .registerModule(JavaTimeModule())
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .setTimeZone(TimeZone.getDefault())
            .setSerializationInclusion(JsonInclude.Include.NON_NULL)
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
}
```

## What did you expect to see?
```kotlin
fun objectMapper(): JsonMapper {
    return JsonMapper.builder()
        .addModule(kotlinModule())
        .defaultTimeZone(TimeZone.getDefault())
        .changeDefaultPropertyInclusion { incl -> incl.withValueInclusion(JsonInclude.Include.NON_NULL) }
        .changeDefaultPropertyInclusion { incl -> incl.withContentInclusion(JsonInclude.Include.NON_NULL) }
        .build()
}

```

## What did you see instead?
```kotlin
fun objectMapper(): ObjectMapper {
    returnObjectMapper()
        .registerKotlinModule()
        .setTimeZone(TimeZone.getDefault())
        .setDefaultPropertyInclusion(JsonInclude.Include.NON_NULL)
}
```

### Before
```kotlin
val objectMapper: ObjectMapper by lazy {
    ObjectMapper()
        .registerKotlinModule()
        .registerModule(JavaTimeModule())
        .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
        .setTimeZone(TimeZone.getDefault())
        .setSerializationInclusion(JsonInclude.Include.NON_NULL)
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
}
```

### After
```kotlin
val objectMapper: ObjectMapper by lazy {ObjectMapper()
        .registerKotlinModule()
        .setTimeZone(TimeZone.getDefault())
        .setDefaultPropertyInclusion(JsonInclude.Include.NON_NULL)
}
```

### Expected
```kotlin
val objectMapper: JsonMapper by lazy {
    JsonMapper.builder()
        .addModule(kotlinModule())
        .defaultTimeZone(TimeZone.getDefault())
        .changeDefaultPropertyInclusion { incl -> incl.withValueInclusion(JsonInclude.Include.NON_NULL) }
        .changeDefaultPropertyInclusion { incl -> incl.withContentInclusion(JsonInclude.Include.NON_NULL) }
        .build()
}
```

### PR DESCRIPTION
**Pull request by timtebeek**
## Summary
- `MigrateMapperSettersToBuilder` now detects fluent chains on `new JsonMapper()` (e.g., `new JsonMapper().setTimeZone(...).registerModule(...)`) and converts them to `JsonMapper.builder()...build()`
- Adds special handling for `setDefaultPropertyInclusion(JsonInclude.Include.X)` to wrap with `JsonInclude.Value.construct(X, X)` since the builder expects a `Value`, not a raw `Include`
- Reorders recipes in `jackson-2-3.yml` so `RemoveRedundantFeatureFlags` and `RemoveBuiltInModuleRegistrations` run before builder migration, ensuring feature flags and built-in modules are removed from fluent chains first

## Test plan
- [x] Added 5 new unit tests for fluent chain scenarios (return statement, field initializer, setTimeZone, raw Include wrapping, unknown method no-change)
- [x] Updated `UpgradeJackson_2_3Test.chainedConfigurationOnNewObjectMapper` integration test expected output
- [x] All existing tests in `MigrateMapperSettersToBuilderTest`, `UpgradeJackson_2_3Test`, `KotlinUpgradeJackson_2_3Test`, `RemoveRedundantFeatureFlagsTest`, and `RemoveBuiltInModuleRegistrationsTest` pass

- Fixes https://github.com/openrewrite/rewrite-jackson/issues/89

### CODE REVIEW

File: src/main/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilder.java [hunk 1]
```diff
@@ -327,7 +316,129 @@ public J.Identifier visitIdentifier(J.Identifier ident, Set<Boolean> set) {
...
+                                    : SetterToBuilderMapping.fromSetter(setter.getName().getSimpleName());
+                            assert mapping != null;
+                            needsJsonIncludeImport |= appendBuilderCall(setter, mapping, templateCode, templateArgs);
+                        }
+                        templateCode.append("\n.build()");
+
+                        maybeAddImport(JSON_MAPPER);
+                        if (needsJsonIncludeImport) {
+                            maybeAddImport(JSON_INCLUDE);
+                        }
```
Comment (steve-aom-elliott) [inline src/main/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilder.java]: Does it actually need to be guarded? I was under the impression that `maybeAddImport(..)` only actually added it if it figured out it really needed it based on the state of the code following applying the template below.

Comment (timtebeek) [reply src/main/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilder.java]: Good call — you're right, `maybeAddImport` already handles that check. Removed the guard and changed `appendBuilderCall` to return `void` since the boolean was only used for the guard. Fixed in 85f7ac8.

File: src/test/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilderTest.java [hunk 2]
```diff
@@ -587,6 +587,168 @@ JsonMapper create() {
...
+                          return new JsonMapper()
+                                  .disable(SerializationFeature.INDENT_OUTPUT)
+                                  .writeValueAsString("test");
+                      }
+                  }
+                  """
+              )
+            );
+        }
+    }
```
Comment (steve-aom-elliott) [inline src/test/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilderTest.java:763]: Wouldn't we have been able to turn it into
```java
return new JsonMapper.builder()
        .disable(SerializationFeature.INDENT_OUTPUT)
        .build()
        .writeValueAsString("test");
```
?

Comment (timtebeek) [reply src/test/java/org/openrewrite/java/jackson/MigrateMapperSettersToBuilderTest.java:763]: Good point! Now the chain is split at the first unknown method — known setters go to the builder, and any remaining calls (like `writeValueAsString`) are chained after `.build()`. Fixed in 5168005.

**Review by steve-aom-elliott — APPROVED** [review]
